Behaviors:
    Robot:
        Sensors:
            Cameras:
                Camera_0:
                    Name: 'camera_0'
                    Topic: '/carla/ego_vehicle/rgb_front/image'
                Camera_1:
                    Name: 'camera_1'
                    Topic: '/carla/ego_vehicle/rgb_view/image'
                Camera_2:
                    Name: 'camera_2'
                    Topic: '/carla/ego_vehicle/semantic_segmentation_front/image'
                Camera_3:
                    Name: 'camera_3'
                    Topic: '/carla/ego_vehicle/dvs_front/image'
            Pose3D:
                Pose3D_0:
                    Name: 'pose3d_0'
                    Topic: '/carla/ego_vehicle/odometry'
            BirdEyeView:
                BirdEyeView_0:
                    Name: 'bird_eye_view_0'
                    Topic: ''
            Speedometer:
                Speedometer_0:
                    Name: 'speedometer_0'
                    Topic: '/carla/ego_vehicle/speedometer'
        Actuators:
            CARLA_Motors:
                Motors_0:
                    Name: 'motors_0'
                    Topic: '/carla/ego_vehicle/vehicle_control_cmd'
                    MaxV: 3
                    MaxW: 0.3
                    
        BrainPath: [
            'brains/CARLA/tensorflow/brain_carla_bird_eye_deep_learning.py',
            'brains/CARLA/pytorch/brain_carla_bird_eye_deep_learning_torch.py',
            ]
        PilotTimeCycle: 50
        AsyncMode: True
        Parameters:
            Model: [
                'pilotnet.h5',
                'pilotnet_model.pth'
                ]
            ImageCropped: True
            ImageSize: [ 100,50 ]
            ImageNormalized: True
            PredictionsNormalized: True
            GPU: True
            UseOptimized: False
            ImageTranform: ''
        Type: 'CARLA'
    Experiment:
        Name: "Experiment name"
        Description: "Experiment description"
        UseWorldTimeouts: True
        Timeout: [10, 10, 10, 10, 10, 10, 10] # for each world!
        Repetitions: 5
    Simulation:
        World: [
            configs/CARLA/CARLA_launch_files/town_01_anticlockwise_no_gui.launch,
            configs/CARLA/CARLA_launch_files/town_02_anticlockwise_no_gui.launch,
            configs/CARLA/CARLA_launch_files/town_03_anticlockwise_no_gui.launch,
            configs/CARLA/CARLA_launch_files/town_04_anticlockwise_no_gui.launch,
            configs/CARLA/CARLA_launch_files/town_05_anticlockwise_no_gui.launch,
            configs/CARLA/CARLA_launch_files/town_06_anticlockwise_no_gui.launch,
            configs/CARLA/CARLA_launch_files/town_07_anticlockwise_no_gui.launch
            ]
        RandomSpawnPoint: False
        SpawnPoints: [
            [
                "10.0, 2.0, 1.37, 0.0, 0.0, 180.0",
                "300.0, -330.0, 1.37, 0.0, 0.0, 0.0",
                "397.0, -50.0, 1.37, 0.0, 0.0, 90.0",
                "392.0, -50.0, 1.37, 0.0, 0.0, -90.0",
                "20.0, -327.0, 1.37, 0.0, 0.0, 180.0"
            ],
            [
                "55.3, -105.6, 1.37, 0.0, 0.0, 180.0",
                "-7.0, -270.6, 1.37, 0.0, 0.0, -90.0",
                "-3.0, -270.6, 1.37, 0.0, 0.0, 90.0",
                "100.0, -303.0, 1.37, 0.0, 0.0, 180.0",
                "190.0, -150.0, 1.37, 0.0, 0.0, -90.0"
            ],
            [
                "246.0, 150.0, 1.37, 0.0, 0.0, 90.0",
                "243.0, -100., 1.37, 0.0, 0.0, 90.0",
                "-88.0, 170, 1.37, 0.0, 0.0, -90.0",
                "232.0, 0.0, 1.37, 0.0, 0.0, -90.0",
                "-50.0, 195, 1.37, 0.0, 0.0, 0.0"
            ],
            [
                "381.5, 60.0, 1.37, 0.0, 0.0, -90.0",
                "-16.0, -184.6, 1.37, 0.0, 0.0, -90.0",
                "381.5, 60.0, 1.37, 0.0, 0.0, -90.0",
                "-16.0, -184.6, 1.37, 0.0, 0.0, -90.0",
                "381.5, 60.0, 1.37, 0.0, 0.0, -90.0"
            ],
            [
                "20, -187.5, 1.37, 0.0, 0.0, 180.0",
                "210.1, -87.3, 1.37, 0.0, 0.0, 90.0",
                "189, -87.3, 1.37, 0.0, 0.0, -90.0",
                "20, -187.5, 1.37, 0.0, 0.0, 180.0",
                "210.1, -87.3, 1.37, 0.0, 0.0, 90.0"
            ],
            [
                "659.0, -70.5, 1.37, 0.0, 0.0, -90.0",
                "351.5, 10.5, 1.37, 0.0, 0.0, 0.0",
                "351.5, 24.5, 1.37, 0.0, 0.0, 180.0",
                "672.5, -70.5, 1.37, 0.0, 0.0, 90.0",
                "659.0, -70.5, 1.37, 0.0, 0.0, -90.0"
            ],
            [
                "-3.0, 243.0, 1.37, 0.0, 0.0, 180.0",
                "70.5, 5.0, 1.37, 0.0, 0.0, 60.0",
                "-184.5, -107.2, 1.37, 0.0, 0.0, 180.0",
                "-3.0, 243.0, 1.37, 0.0, 0.0, 180.0",
                "70.5, 5.0, 1.37, 0.0, 0.0, 60.0"
            ]
        ]
    Dataset:
        In: '/tmp/my_bag.bag'
        Out: ''
    Stats:
        Out: './'
        PerfectLap: './perfect_bags/lap-simple-circuit.bag'
    Layout:
        Frame_0:
            Name: frame_0
            Geometry: [1, 1, 1, 1]
            Data: rgbimage
        Frame_1:
            Name: frame_1
            Geometry: [0, 1, 1, 1]
            Data: rgbimage
        Frame_2:
            Name: frame_2
            Geometry: [0, 2, 1, 1]
            Data: rgbimage
        Frame_3:
            Name: frame_3
            Geometry: [1, 2, 1, 1]
            Data: rgbimage
