# This is a basic workflow to help you get started with Actions

name: Publish cuda 11 Docker image

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the noetic-devel branch
on:
  push:
    branches: [ noetic-devel ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  push_to_registry:
    name: Push cuda 11 Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2 
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jderobot/behavior-metrics:noetic-cuda11
          context: .docker/noetic/
          file: .docker/noetic/Dockerfile-cuda11
